#!/usr/bin/env python

import sys
sys.path.append("../bleichenbacher_oracle_example/RSA_manager")
import rsa_manager
import math_module

l = math_module.extended_euclidean_algorithm(41, -15)
print(l, end="\n*********************\n\n")
l = math_module.lagrange_coefficient([7,19,22], 41)
print(l)
